set_property MARK_DEBUG true [get_nets image_processing_2d_design_i/frequency_analyzer_manager_0/pixel_clock]
set_property MARK_DEBUG true [get_nets image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel0_sample_data]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[5]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[8]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[10]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[9]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[7]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[1]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[4]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[0]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[3]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[6]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[11]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[2]}]

set_property MARK_DEBUG false [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/light_threshold[7]_i_3_n_0}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/light_threshold_reg_n_0_[3]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/light_threshold_reg_n_0_[5]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/light_threshold_reg_n_0_[2]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/light_threshold_reg_n_0_[6]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/light_threshold_reg_n_0_[0]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/light_threshold_reg_n_0_[1]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/light_threshold_reg_n_0_[7]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/light_threshold_reg_n_0_[4]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list image_processing_2d_design_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 12 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[0]} {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[1]} {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[2]} {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[3]} {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[4]} {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[5]} {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[6]} {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[7]} {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[8]} {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[9]} {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[10]} {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter_reg[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {image_processing_2d_design_i/linescanner_image_capture_unit_0_pixel_data[0]} {image_processing_2d_design_i/linescanner_image_capture_unit_0_pixel_data[1]} {image_processing_2d_design_i/linescanner_image_capture_unit_0_pixel_data[2]} {image_processing_2d_design_i/linescanner_image_capture_unit_0_pixel_data[3]} {image_processing_2d_design_i/linescanner_image_capture_unit_0_pixel_data[4]} {image_processing_2d_design_i/linescanner_image_capture_unit_0_pixel_data[5]} {image_processing_2d_design_i/linescanner_image_capture_unit_0_pixel_data[6]} {image_processing_2d_design_i/linescanner_image_capture_unit_0_pixel_data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/light_threshold[7]_i_3_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/light_threshold_reg_n_0_[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/light_threshold_reg_n_0_[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/light_threshold_reg_n_0_[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/light_threshold_reg_n_0_[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/light_threshold_reg_n_0_[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/light_threshold_reg_n_0_[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/light_threshold_reg_n_0_[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/light_threshold_reg_n_0_[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel0_sample_data]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list image_processing_2d_design_i/frequency_analyzer_manager_0/pixel_clock]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
