set_property MARK_DEBUG true [get_nets image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel0_sample_data_reg_n_0]

set_property MARK_DEBUG true [get_nets image_processing_2d_design_i/linescanner_image_capture_unit_0_pixel_captured]
set_property MARK_DEBUG true [get_nets image_processing_2d_design_i/LINESCANNER0_MAIN_CLOCK]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter[1]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter[2]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter[3]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter[4]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter[5]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter[6]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter[7]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter[8]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter[9]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter[12]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter[10]}]
set_property MARK_DEBUG true [get_nets {image_processing_2d_design_i/frequency_analyzer_manager_0/inst/pixel_counter[11]}]

connect_debug_port u_ila_0/probe1 [get_nets [list {image_processing_2d_design_i/linescanner_image_capture_unit_0_pixel_data[0]} {image_processing_2d_design_i/linescanner_image_capture_unit_0_pixel_data[1]} {image_processing_2d_design_i/linescanner_image_capture_unit_0_pixel_data[2]} {image_processing_2d_design_i/linescanner_image_capture_unit_0_pixel_data[3]} {image_processing_2d_design_i/linescanner_image_capture_unit_0_pixel_data[4]} {image_processing_2d_design_i/linescanner_image_capture_unit_0_pixel_data[5]} {image_processing_2d_design_i/linescanner_image_capture_unit_0_pixel_data[6]} {image_processing_2d_design_i/linescanner_image_capture_unit_0_pixel_data[7]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list image_processing_2d_design_i/linescanner_image_capture_unit_0_pixel_captured]]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]

